### ISSUE TITLE
CGO_ENABLED=0

### ISSUE THREAD

**Issue by NiklasKy** [OCAP2/OCAP#79]
Hi, I'm trying to install OCAP on a Windows Server.
I installed everything according to the guide but when I try to run the OCAP-webserver.exe I get an error when it's trying to create the Database.

```
panic: could be create table operation: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

goroutine 1 [running]:
main.check(...)
        C:/A3OCAP/cmd/main.go:14
main.main()
        C:/A3OCAP/cmd/main.go:23 +0x694
```
        
I also tried to set the variable for CGO to 1 but that didn't change anything.
Does someone know how to fix that?

![image](https://github.com/OCAP2/OCAP/assets/62724509/bed6b68f-7a4e-4f6b-b943-7a77467b582c)

**Comment by NiklasKy** [comment]
I fixed it myself. 
the `go build -o ocap-webserver.exe ./src/web` command on the [web tree](https://github.com/OCAP2/web/tree/b273a4d6e587862e0a2fb4c2b2c8ba79240ebc42) looks wrong.

I used `go build -o ocap-webserver.exe ./cmd/main.go` and now it works

**Comment by NiklasKy** [comment]
I fixed it myself.
the `go build -o ocap-webserver.exe ./src/web` command on the [web tree](https://github.com/OCAP2/web/tree/b273a4d6e587862e0a2fb4c2b2c8ba79240ebc42) looks wrong.

I used `go build -o ocap-webserver.exe ./cmd/main.go` and now it works
